function toast(message,type="info",duration=3200){let host=$("toastHost");if(!host){host=document.createElement("div");host.id="toastHost";host.className="toast-host";document.body.appendChild(host)}const el=document.createElement("div");el.className="toast toast-"+type;el.textContent=message;host.appendChild(el);requestAnimationFrame(()=>el.classList.add("show"));setTimeout(()=>{el.classList.remove("show");setTimeout(()=>el.remove(),250)},duration)}
function api(path,options={}){const notify=options.notify!==false,method=(options.method||"GET").toUpperCase(),fetchOptions={...options};delete fetchOptions.notify;if(notify&&method!=="GET")toast("Working…","loading",1500);return fetch(path,{...fetchOptions,headers:{"Content-Type":"application/json",...(fetchOptions.headers||{})}}).then(async r=>{if(!r.ok){let detail="Request failed.";try{detail=(await r.clone().json()).detail||detail}catch{}if(notify)toast(detail,"error")}else if(notify&&method!=="GET")toast("Operation completed.","success");return r}).catch(err=>{if(notify)toast("Network error. Check the server.","error");throw err})}
const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const todayKey=()=>new Date().toISOString().slice(0,10),formatTime=s=>new Date(s*1000).toISOString().slice(11,19);
let clientSeconds=0,serverSeconds=0,logOffset=0,logSearchTimer=null;
function loadUsage(){try{const d=JSON.parse(localStorage.getItem("mpa_usage")||"{}");clientSeconds=d.date===todayKey()?Number(d.seconds||0):0}catch{clientSeconds=0}}
function saveUsage(){localStorage.setItem("mpa_usage",JSON.stringify({date:todayKey(),seconds:clientSeconds}))}
function updateClientUsage(){clientSeconds++;saveUsage()}
function renderServerUsage(d){serverSeconds=Number(d.server_runtime_seconds||0);const pct=Math.min(100,serverSeconds/Number(d.limit_seconds||28800)*100);document.querySelectorAll("[data-usage-time]").forEach(e=>e.textContent=formatTime(serverSeconds));document.querySelectorAll("[data-usage-percent]").forEach(e=>e.textContent=Math.round(pct)+"%");document.querySelectorAll("[data-usage-bar]").forEach(e=>e.style.width=pct+"%");if($("serverUsageMeta"))$("serverUsageMeta").textContent="Server runtime: "+formatTime(serverSeconds)+" · "+d.percent+"% of 8-hour reference"}
async function loadServerUsage(){try{const r=await api("/api/usage",{notify:false});if(r.ok)renderServerUsage(await r.json())}catch{}}
async function loadSettings(){const r=await api("/api/settings",{notify:false});if(!r.ok)return;const c=await r.json();document.querySelectorAll("[data-brand-name]").forEach(e=>e.textContent=c.platform_name||"My Personal Assistant");document.querySelectorAll("[data-brand-logo]").forEach(e=>e.textContent=c.logo||"🤖");if($("platformName"))$("platformName").value=c.platform_name||"";if($("logo"))$("logo").value=c.logo||"";if($("geminiKey"))$("geminiKey").value="";if($("geminiModel"))$("geminiModel").value=c.gemini_model||"gemini-3.7-flash";if($("scrapeInterval"))$("scrapeInterval").value=c.scrape_interval_minutes||60;if($("defaultMode"))$("defaultMode").value=c.default_storage_mode||"append";if($("storageMode"))$("storageMode").value=c.default_storage_mode||"append"}
async function health(){try{const r=await api("/api/health",{notify:false}),d=await r.json();if($("serverStatus"))$("serverStatus").textContent=d.status;if($("dashServer"))$("dashServer").textContent=d.status==="online"?"Online":"Degraded";if($("statusMessage"))$("statusMessage").textContent="API is responding normally."}catch{if($("serverStatus"))$("serverStatus").textContent="offline";if($("dashServer"))$("dashServer").textContent="Offline"}}
async function loadFiles(){const r=await api("/api/excel",{notify:false});if(!r.ok)return;const d=await r.json();if($("fileCount"))$("fileCount").textContent=d.files.length;if($("excelList"))$("excelList").innerHTML=d.files.length?d.files.map(f=>'<div class="panel p-4 flex flex-wrap items-center justify-between gap-3"><div><div class="font-semibold">'+esc(f.file_name)+'</div><div class="muted text-xs">'+Math.max(1,Math.round(f.size_bytes/1024))+" KB · "+new Date(f.modified).toLocaleString()+'</div></div><a class="secondary inline-block" href="/api/download-excel/'+encodeURIComponent(f.file_name)+'">Download Excel</a></div>').join(""):'<div class="panel p-5 muted">No Excel files yet.</div>'}
const LOG_PAGE_SIZE=100;
async function loadLogs(reset=true){if(!$("logList"))return;if(reset)logOffset=0;const p=new URLSearchParams({q:($("logSearch")?.value||"").trim(),platform:$("logPlatform")?.value||"",date_from:$("logDateFrom")?.value||"",date_to:$("logDateTo")?.value||"",limit:String(LOG_PAGE_SIZE),offset:String(logOffset)}),r=await api("/api/logs/search?"+p,{notify:false});if(!r.ok)return;const d=await r.json();$("logList").innerHTML=d.records.length?d.records.map(x=>'<article class="bubble log-bubble"><div class="meta">'+esc(x.Date)+" · "+esc(x.Time)+" · "+esc(x.Platform)+'</div><div class="font-semibold">'+esc(x["Prompt/Topic"])+'</div><div class="muted text-sm mt-1">File: '+esc(x["File Name"])+'</div><div class="text-sm mt-2">'+esc(x["Message Bubble"])+"</div></article>").join(""):'<div class="panel p-6 muted">No matching records.</div>';const from=d.total?d.offset+1:0,to=Math.min(d.offset+d.limit,d.total);if($("logSummary"))$("logSummary").textContent=`Showing ${from}–${to} of ${d.total} records`;if($("logPrev"))$("logPrev").disabled=d.offset===0;if($("logNext"))$("logNext").disabled=d.offset+d.limit>=d.total}
function initLogFilters(){if(!$("logList"))return;const refresh=()=>{clearTimeout(logSearchTimer);logSearchTimer=setTimeout(()=>loadLogs(true),250)};["logSearch","logPlatform","logDateFrom","logDateTo"].forEach(id=>$(id)?.addEventListener(id==="logSearch"?"input":"change",refresh));$("logPrev")?.addEventListener("click",()=>{logOffset=Math.max(0,logOffset-LOG_PAGE_SIZE);loadLogs(false)});$("logNext")?.addEventListener("click",()=>{logOffset+=LOG_PAGE_SIZE;loadLogs(false)});$("refreshLogs")?.addEventListener("click",()=>loadLogs(true));loadLogs()}
function initScraper(){if(!$("openScraper"))return;$("openScraper").onclick=()=>$("scrapeModal").classList.remove("hidden");$("closeScraper").onclick=()=>$("scrapeModal").classList.add("hidden");$("scrapeForm").onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const r=await api("/api/scrape",{method:"POST",body:JSON.stringify({topic:$("topic").value,platform:$("platform").value,storage_mode:$("storageMode").value,file_name:$("fileName").value})});const d=await r.json();$("scrapeModal").classList.add("hidden");$("scrapeResult").classList.remove("hidden");$("scrapeResult").textContent=r.ok?`Saved ${d.rows_added} record(s) to ${d.file_name}; total rows: ${d.total_rows}.`:(d.detail||"Scrape failed.")}finally{btn.disabled=false}}}
function initAdmin(){if(!$("settingsForm"))return;$("settingsForm").onsubmit=async e=>{e.preventDefault();const payload={platform_name:$("platformName").value,logo:$("logo").value,gemini_api_key:$("geminiKey").value,gemini_model:$("geminiModel").value,default_storage_mode:$("defaultMode").value,scrape_interval_minutes:Number($("scrapeInterval")?.value||60)},r=await api("/api/admin/config",{method:"POST",headers:{"X-Admin-Config-Secret":$("adminConfigSecret")?.value||""},{method:"POST",body:JSON.stringify(payload)});if(r.ok){await loadSettings();$("settingsMessage").textContent="Saved successfully."}else{$("settingsMessage").textContent="Save failed."}}}
function bubble(text,type){const el=document.createElement("div");el.className="bubble "+type;el.innerHTML=esc(text).replace(/\n/g,"<br>");$("chatMessages").appendChild(el);$("chatMessages").scrollTop=$("chatMessages").scrollHeight;return el}
function speak(text){if("speechSynthesis" in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text))}}
function initVoice(){const btn=$("voiceBtn"),input=$("chatInput");if(!btn||!input)return;const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){btn.disabled=true;btn.title="Speech recognition is not supported in this browser";return}const recognition=new SpeechRecognition();recognition.lang=document.documentElement.lang||"en-US";recognition.interimResults=false;recognition.continuous=false;btn.onclick=()=>{try{recognition.start();toast("Listening…","loading",1500)}catch{}};recognition.onresult=e=>{input.value=e.results[0][0].transcript;input.focus()};recognition.onerror=()=>toast("Voice input failed.","error")}
async function sendChat(msg){if(!msg)return;const input=$("chatInput");if(input)input.value="";bubble(msg,"user");const pending=bubble("Thinking…","ai");try{const r=await api("/api/chat",{method:"POST",body:JSON.stringify({message:msg,include_logs:true})}),d=await r.json();pending.remove();const answer=r.ok?(d.answer||"No response."):(d.detail||"Chat request failed.");bubble(answer,"ai");if(r.ok)speak(answer)}catch{pending.remove();bubble("Request failed. Check the server.","ai")}}
function initChat(){if(!$("chatForm"))return;$("chatForm").onsubmit=e=>{e.preventDefault();sendChat($("chatInput").value.trim())};initVoice();document.querySelectorAll("[data-quick-action]").forEach(b=>b.addEventListener("click",()=>sendChat(b.dataset.quickAction)));$("workflowBtn")?.addEventListener("click",async()=>{const msg=$("chatInput").value.trim();if(!msg)return toast("Enter a task first.","error");const r=await api("/api/agents/workflow",{method:"POST",body:JSON.stringify({message:msg,include_logs:true})});const d=await r.json();if(r.ok){bubble(d.workflow.report_writer_agent,"ai");speak(d.workflow.report_writer_agent)}})}
function initBackup(){if(!$("backupBtn"))return;$("backupBtn").onclick=async()=>{const btn=$("backupBtn");btn.disabled=true;btn.textContent="Creating…";try{const r=await api("/api/backup",{method:"POST"});if(!r.ok)throw new Error("Backup failed");const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="system_backup.zip";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){toast(e.message,"error")}finally{btn.disabled=false;btn.textContent="Create ZIP Backup"}}}
async function loadAutomation(){if(!$("automationScheduler"))return;try{const r=await api("/api/automation",{notify:false});if(!r.ok)return;const d=await r.json();$("automationScheduler").textContent=d.scheduler.enabled?"Running":"Disabled";$("automationTelegram").textContent=d.telegram.configured?"Configured":"Not configured";$("automationBackup").textContent=d.backup.latest||"No backup yet";$("automationJobs").textContent=(d.scheduler.jobs||[]).map(j=>j.id+" → "+(j.next_run||"not scheduled")).join(" · ")||"No scheduled jobs."}catch{}}
function navigation(){const items=[["index.html","📊","Dashboard"],["scraper.html","🔎","Scraper"],["logs.html","💬","Data Logs"],["chat.html","🧠","AI Chat"],["admin.html","⚙️","Admin Settings"],["backup.html","💾","Backups & Downloads"]],current=location.pathname.split("/").pop()||"index.html";document.querySelectorAll("[data-navigation]").forEach(n=>n.innerHTML='<nav class="panel nav-panel">'+items.map(([href,icon,label])=>'<a class="nav-link '+(current===href?"active":"")+'" href="/'+href+'"><span>'+icon+'</span><span>'+label+"</span></a>").join("")+"</nav>")}
loadUsage();navigation();loadServerUsage();loadSettings();health();if($("fileCount")||$("excelList"))loadFiles();if($("logList"))initLogFilters();if($("openScraper"))initScraper();if($("settingsForm"))initAdmin();loadAutomation();if($("chatForm"))initChat();if($("backupBtn"))initBackup();if($("dashServer"))setInterval(health,30000);setInterval(updateClientUsage,1000);setInterval(loadServerUsage,30000);